#!/usr/bin/env bash
# Configure ufw to allow only SSH (22), HTTP (80), and HTTPS (443)

ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw enable
ufw status verbose
