#!/usr/bin/env bash
# Configure Apache to serve a page containing 'Hello Holberton'

# Install Apache if it is not installed
apt-get update -y
apt-get install -y apache2

# Create the index page
printf "Hello Holberton\n" > /var/www/html/index.html

# Start Apache
service apache2 start
